package cl.subox.ms.aud.domain.enums;

import cl.bch.cloud.commons.error.domains.IError;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.HashMap;
import java.util.Map;

import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ACTIVA_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ACTUALIZAR_DISPOSITIVO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_AGREGAR_DISPOSITIVO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ANULAR_OPORTUNIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_BIOMETRIA_IMAGENES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_CATEGORIAS_TALLER;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_CONFIG_FIRMA_ESIGN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_CREA_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_DETALLE_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_DETALLE_TALLER;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENCRIPTA_PDF;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_IDG;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_CAMBIOCLAVE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_DESBLOQUEO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_PRIMERLOGIN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_CORE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_MDM;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_RESETEOCLAVE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_ENVIO_MAIL;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_FIRMA_ESIGN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_PLANTILLA_DOCUMENTO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_SOLICITUD_FIRMA_ESIGN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_CONEXION_SUBIR_DOCUMENTO_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_GENERAL;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_OPORTUNIDAD_ACTIVA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_OPORTUNIDAD_SUBIR_DOCUMENTO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_PIN_NOT_MATCH;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ACTIVA_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ACTUALIZAR_DISPOSITIVO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_AGREGAR_DISPOSITIVO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ANULAR_OPORTUNIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_BIOMETRIA_IMAGENES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_CATEGORIAS_TALLER;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_CONFIG_FIRMA_ESIGN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_CREA_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_DETALLE_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_DETALLE_TALLER;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENCRIPTA_PDF;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_IDG;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_CAMBIOCLAVE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_DESBLOQUEO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_PRIMERLOGIN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_CORE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_MDM;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_RESETEOCLAVE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_ENVIO_MAIL;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_FIRMA_ESIGN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_PLANTILLA_DOCUMENTO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_SOLICITUD_FIRMA_ESIGN;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_SERVIDOR_SUBIR_DOCUMENTO_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_TALLER_PRODUCTO_CATEGORIA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_TALLER_PRODUCTO_REGLA_CON_APLICADA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_API_VENTA_TALLER_PRODUCTO_REGLA_SIN_APLICADA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_BIOMETRIA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_CLIENTE_PLATINUM;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_CONSULTA_DISPOSITIVOS;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_CONSULTA_INF_BASICA_LAB;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_CONSULTA_PRODUCTOS;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_DEPURADOR;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_DETALLE_OPORTUNIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_FICHA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_FICHA_BASICA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_INHABILIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_LISTA_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_OFAC_RIESGO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_OFFERTS_INTERACT;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_POSTEVENT_INTERACT;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_PREGUNTAS_SEGURIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_PREVIRED_CLIENTE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_PRODUCTOS_CLIENTE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_PROFILE_INTERACT;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_RECAPTCHA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_TOKEN_CHALLENGE_PREGUNTAS_SEGURIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_VALIDACION_PREGUNTAS_SEGURIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_CONEXION_API_AUTORIZACION_VECTOR;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_BIOMETRIA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_CLIENTE_FICHA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_CLIENTE_PLATINUM;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_CLIENTE_VECTOR;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_CONSULTA_DISPOSITIVOS;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_CONSULTA_PRODUCTOS;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_DEPURADOR;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_DETALLE_OPORTUNIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_FICHA_BASICA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_INFO_BASICA_LAB;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_INHABILIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_LISTA_OPORTUNIDADES;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_OFAC_RIESGO;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_OFFERTS_INTERACT;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_POSTEVENT_INTERACT;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_PREGUNTAS_SEGURIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_PREVIRED_CLIENTE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_PRODUCTOS_CLIENTE;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_PROFILE_INTERACT;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_RECAPTCHA;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_TOKEN_CHALLENGE_PREGUNTAS_SEGURIDAD;
import static cl.bch.cloud.productos.cuentacorrientedigital.bff.enums.ECatalogo.ERROR_SERVIDOR_API_AUTORIZACION_VALIDACION_PREGUNTAS_SEGURIDAD;

@AllArgsConstructor
@Getter
public enum ESubcatalogo {

    /* Errores autenticacion */
    API_AUTORIZACION_CLIENTE_CON_CUENTA_CORRIENTE("MAPRE_001",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_CC),
    API_AUTORIZACION_CLIENTE_CEDULA_INCORRECTA("MAPRE_002",
            ECatalogo.ERROR_API_AUTORIZACION_CEDULA_INCORRECTA),
    API_AUTORIZACION_CLIENTE_CEDULA_NO_VIGENTE("MAPRE_003",
            ECatalogo.ERROR_API_AUTORIZACION_CEDULA_NO_VIGENTE),
    API_AUTORIZACION_NO_DISPONIBLE("MAPRE_004",
            ECatalogo.ERROR_API_AUTORIZACION_CEDULA_NO_DISPONIBLE),
    API_AUTORIZACION_CLIENTE_CON_OPORTUNIDAD("MAPRE_005",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_CON_OPORTUNIDAD),
    API_AUTORIZACION_CLIENTE_NO_POSEE_OFERTAS("MAPRE_006",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_SIN_OFERTAS),
    API_AUTORIZACION_CLIENTE_NO_EXISTE_INTERACT("MAPRE_007",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_NO_EXISTE_INTERACT),
    API_AUTORIZACION_CLIENTE_INHABIL("MAPRE_008",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_CON_INHABILIDAD),
    API_AUTORIZACION_CLIENTE_OFAC("MAPRE_009",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_OFAC),
    API_AUTORIZACION_CLIENTE_MENOR_EDAD("MAPRE_010",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_MENOR_EDAD),
    API_AUTORIZACION_CLIENTE_MORA("MAPRE_011",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_CON_INHABILIDAD),
    API_AUTORIZACION_CLIENTE_INVALIDO_IDG("MAPRE_012",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_INVALIDO_IDG),
    API_AUTORIZACION_CLIENTE_RENTA_NO_SUFICIENTE("MAREN_001",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_RENTA_INSUFICIENTE),
    API_AUTORIZACION_CLIENTE_CONTACTABILIDAD_CELULAR_EXISTENTE("MAING_001",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_CELULAR_EXISTENTE),
    API_AUTORIZACION_CLIENTE_CONTACTABILIDAD_EMAIL_EXISTENTE("MAING_002",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_EMAIL_EXISTENTE),
    API_AUTORIZACION_CLIENTE_CONTACTABILIDAD_CELULAR_EMAIL_EXISTENTE("MAING_000",
            ECatalogo.ERROR_API_AUTORIZACION_CLIENTE_CELULAR_EMAIL_EXISTENTE),
    API_AUTORIZACION_DESAFIO_SIN_PREGUNTAS_SEGURIDAD("MAPRG_003",
            ECatalogo.ERROR_API_AUTORIZACION_DESAFIO_SIN_PREGUNTAS_SEGURIDAD),
    API_AUTORIZACION_DESAFIO_DIARIO_PREGUNTAS_ALCANZADO("MAPRG_001",
            ECatalogo.ERROR_API_AUTORIZACION_DESAFIO_DIARIO_PREGUNTAS_ALCANZADO),
    API_AUTORIZACION_DESAFIO_VALIDACION_PREGUNTAS("MAPRG_002",
            ECatalogo.ERROR_API_AUTORIZACION_DESAFIO_VALIDACION_PREGUNTAS_RESPUESTAS_INCORRECTAS),

    /* ERRORES CONEXION APIS */

    API_AUTORIZACION_CONEXION_OFAC_RIESGO("MACON_001",
            ERROR_CONEXION_API_AUTORIZACION_OFAC_RIESGO),
    API_AUTORIZACION_CONEXION_CLIENTE_FICHA("MACON_002",
            ERROR_CONEXION_API_AUTORIZACION_FICHA),
    API_AUTORIZACION_CONEXION_CLIENTE_VECTOR("MACON_003",
            ERROR_CONEXION_API_AUTORIZACION_VECTOR),
    API_AUTORIZACION_CONEXION_LISTA_OPORTUNIDADES("MACON_004",
            ERROR_CONEXION_API_AUTORIZACION_LISTA_OPORTUNIDADES),
    API_AUTORIZACION_CONEXION_DETALLE_OPORTUNIDAD("MACON_005",
            ERROR_CONEXION_API_AUTORIZACION_DETALLE_OPORTUNIDAD),
    API_AUTORIZACION_CONEXION_PROFILE_INTERACT("MACON_006",
            ERROR_CONEXION_API_AUTORIZACION_PROFILE_INTERACT),
    API_AUTORIZACION_CONEXION_OFFERTS_INTERACT("MACON_007",
            ERROR_CONEXION_API_AUTORIZACION_OFFERTS_INTERACT),
    API_AUTORIZACION_CONEXION_POSTEVENT_INTERACT("MACON_008",
            ERROR_CONEXION_API_AUTORIZACION_POSTEVENT_INTERACT),
    API_AUTORIZACION_CONEXION_PRODUCTOS_CLIENTE("MACON_009",
            ERROR_CONEXION_API_AUTORIZACION_PRODUCTOS_CLIENTE),
    API_AUTORIZACION_CONEXION_RECAPTCHA("MACON_010",
            ERROR_CONEXION_API_AUTORIZACION_RECAPTCHA),
    API_AUTORIZACION_CONEXION_PREVIRED_CLIENTE("MACON_011",
            ERROR_CONEXION_API_AUTORIZACION_PREVIRED_CLIENTE),
    API_AUTORIZACION_CONEXION_DEPURADOR("MACON_012",
            ERROR_CONEXION_API_AUTORIZACION_DEPURADOR),
    API_AUTORIZACION_CONEXION_INHABILIDADES("MACON_013",
            ERROR_CONEXION_API_AUTORIZACION_INHABILIDADES),
    API_AUTORIZACION_CONEXION_TOKEN_CHALLENGE_PREGUNTAS_SEGURIDAD("MACON_014",
            ERROR_CONEXION_API_AUTORIZACION_TOKEN_CHALLENGE_PREGUNTAS_SEGURIDAD),
    API_AUTORIZACION_CONEXION_PREGUNTAS_SEGURIDAD("MACON_015",
            ERROR_CONEXION_API_AUTORIZACION_PREGUNTAS_SEGURIDAD),
    API_AUTORIZACION_CONEXION_VALIDACION_PREGUNTAS_SEGURIDAD("MACON_016",
            ERROR_CONEXION_API_AUTORIZACION_VALIDACION_PREGUNTAS_SEGURIDAD),
    API_AUTORIZACION_CONEXION_CLIENTE_BOLETIN_PLATINUM("MACON_017",
            ERROR_CONEXION_API_AUTORIZACION_CLIENTE_PLATINUM),
    API_AUTORIZACION_CONEXION_BIOMETRIA("MACON_018",
            ERROR_CONEXION_API_AUTORIZACION_BIOMETRIA),
    API_AUTORIZACION_CONEXION_FICHA_BASICA("MACON_019",
            ERROR_CONEXION_API_AUTORIZACION_FICHA_BASICA),
    API_AUTORIZACION_CONEXION_CONSULTA_PRODUCTOS("MACON_020",
            ERROR_CONEXION_API_AUTORIZACION_CONSULTA_PRODUCTOS),
    API_AUTORIZACION_CONEXION_CONSULTA_DISPOSITIVOS("MACON_021",
            ERROR_CONEXION_API_AUTORIZACION_CONSULTA_DISPOSITIVOS),
    API_AUTORIZACION_CONEXION_CONSULTA_INF_BASICA_LAB("MACON_022",
            ERROR_CONEXION_API_AUTORIZACION_CONSULTA_INF_BASICA_LAB),

    /* ERRORES SERVIDOR APIS */

    API_AUTORIZACION_SERVIDOR_OFAC_RIESGO("MASER_001",
            ERROR_SERVIDOR_API_AUTORIZACION_OFAC_RIESGO),
    API_AUTORIZACION_SERVIDOR_CLIENTE_FICHA("MASER_002",
            ERROR_SERVIDOR_API_AUTORIZACION_CLIENTE_FICHA),
    API_AUTORIZACION_SERVIDOR_CLIENTE_VECTOR("MASER_003",
            ERROR_SERVIDOR_API_AUTORIZACION_CLIENTE_VECTOR),
    API_AUTORIZACION_SERVIDOR_LISTA_OPORTUNIDADES("MASER_004",
            ERROR_SERVIDOR_API_AUTORIZACION_LISTA_OPORTUNIDADES),
    API_AUTORIZACION_SERVIDOR_DETALLE_OPORTUNIDAD("MASER_005",
            ERROR_SERVIDOR_API_AUTORIZACION_DETALLE_OPORTUNIDAD),
    API_AUTORIZACION_SERVIDOR_PROFILE_INTERACT("MASER_006",
            ERROR_SERVIDOR_API_AUTORIZACION_PROFILE_INTERACT),
    API_AUTORIZACION_SERVIDOR_OFFERTS_INTERACT("MASER_007",
            ERROR_SERVIDOR_API_AUTORIZACION_OFFERTS_INTERACT),
    API_AUTORIZACION_SERVIDOR_POSTEVENT_INTERACT("MASER_008",
            ERROR_SERVIDOR_API_AUTORIZACION_POSTEVENT_INTERACT),
    API_AUTORIZACION_SERVIDOR_PRODUCTOS_CLIENTE("MASER_009",
            ERROR_SERVIDOR_API_AUTORIZACION_PRODUCTOS_CLIENTE),
    API_AUTORIZACION_SERVIDOR_RECAPTCHA("MASER_010",
            ERROR_SERVIDOR_API_AUTORIZACION_RECAPTCHA),
    API_AUTORIZACION_SERVIDOR_PREVIRED_CLIENTE("MASER_011",
            ERROR_SERVIDOR_API_AUTORIZACION_PREVIRED_CLIENTE),
    API_AUTORIZACION_SERVIDOR_DEPURADOR("MASER_012",
            ERROR_SERVIDOR_API_AUTORIZACION_DEPURADOR),
    API_AUTORIZACION_SERVIDOR_TOKEN_CHALLENGE_PREGUNTAS_SEGURIDAD("MASER_013",
            ERROR_SERVIDOR_API_AUTORIZACION_TOKEN_CHALLENGE_PREGUNTAS_SEGURIDAD),
    API_AUTORIZACION_SERVIDOR_PREGUNTAS_SEGURIDAD("MASER_014",
            ERROR_SERVIDOR_API_AUTORIZACION_PREGUNTAS_SEGURIDAD),
    API_AUTORIZACION_SERVIDOR_VALIDACION_PREGUNTAS_SEGURIDAD("MASER_015",
            ERROR_SERVIDOR_API_AUTORIZACION_VALIDACION_PREGUNTAS_SEGURIDAD),
    API_AUTORIZACION_SERVIDOR_API_CLIENTE_PLATINUM("MASER_016",
            ERROR_SERVIDOR_API_AUTORIZACION_CLIENTE_PLATINUM),
    API_AUTORIZACION_SERVIDOR_API_BIOMETRIA("BFSER_017",
            ERROR_SERVIDOR_API_AUTORIZACION_BIOMETRIA),
    API_AUTORIZACION_SERVIDOR_API_FICHA_BASICA("MASER_018",
            ERROR_SERVIDOR_API_AUTORIZACION_FICHA_BASICA),
    API_AUTORIZACION_SERVIDOR_API_CONSULTA_PRODUCTOS("BFSER_019",
            ERROR_SERVIDOR_API_AUTORIZACION_CONSULTA_PRODUCTOS),
    API_AUTORIZACION_SERVIDOR_API_CONSULTA_DISPOSITIVOS("BFSER_020",
            ERROR_SERVIDOR_API_AUTORIZACION_CONSULTA_DISPOSITIVOS),
    API_AUTORIZACION_SERVIDOR_API_INHABILIDADES("BFSER_021",
            ERROR_SERVIDOR_API_AUTORIZACION_INHABILIDADES),
    API_AUTORIZACION_SERVIDOR_API_INFO_BASICA_LAB("BFSER_022",
            ERROR_SERVIDOR_API_AUTORIZACION_INFO_BASICA_LAB),

    /* VENTA */
    API_VENTA_DEFAULT_ERROR("MSVEN_001", ERROR_API_VENTA_GENERAL),
    API_VENTA_TALLER_PRODUCTO_CATEGORIA("MSVEN_004",
            ERROR_API_VENTA_TALLER_PRODUCTO_CATEGORIA),
    API_VENTA_TALLER_PRODUCTO_REGLA_SIN_APLICADA("MSVEN_005",
            ERROR_API_VENTA_TALLER_PRODUCTO_REGLA_SIN_APLICADA),
    API_VENTA_TALLER_PRODUCTO_REGLA_CON_APLICADA("MSVEN_006",
            ERROR_API_VENTA_TALLER_PRODUCTO_REGLA_CON_APLICADA),
    API_VENTA_OPORTUNIDAD_ACTIVA("MSVEN_007",
            ERROR_API_VENTA_OPORTUNIDAD_ACTIVA),
    API_VENTA_OPORTUNIDAD_SUBIR_DOCUMENTO("MSVEN_008",
            ERROR_API_VENTA_OPORTUNIDAD_SUBIR_DOCUMENTO),
    API_VENTA_PIN_NOT_MATCH_RUT("MSVEN_018", ERROR_API_VENTA_PIN_NOT_MATCH),
    API_VENTA_CONEXION_CONFIG_FIRMA_ESIGN("MSVCO_001",
            ERROR_API_VENTA_CONEXION_CONFIG_FIRMA_ESIGN),
    API_VENTA_CONEXION_SOLICITUD_FIRMA_ESIGN("MSVCO_002",
            ERROR_API_VENTA_CONEXION_SOLICITUD_FIRMA_ESIGN),
    API_VENTA_CONEXION_FIRMA_ESIGN("MSVCO_003",
            ERROR_API_VENTA_CONEXION_FIRMA_ESIGN),
    API_VENTA_CONEXION_DETALLE_OPORTUNIDADES("MSVCO_004",
            ERROR_API_VENTA_CONEXION_DETALLE_OPORTUNIDADES),
    API_VENTA_CONEXION_SUBIR_DOCUMENTO_OPORTUNIDADES("MSVCO_005",
            ERROR_API_VENTA_CONEXION_SUBIR_DOCUMENTO_OPORTUNIDADES),
    API_VENTA_CONEXION_CREA_OPORTUNIDADES("MSVCO_006",
            ERROR_API_VENTA_CONEXION_CREA_OPORTUNIDADES),
    API_VENTA_CONEXION_ACTIVA_OPORTUNIDADES("MSVCO_007",
            ERROR_API_VENTA_CONEXION_ACTIVA_OPORTUNIDADES),
    API_VENTA_CONEXION_CATEGORIAS_TALLER("MSVCO_008",
            ERROR_API_VENTA_CONEXION_CATEGORIAS_TALLER),
    API_VENTA_CONEXION_DETALLE_TALLER("MSVCO_009",
            ERROR_API_VENTA_CONEXION_DETALLE_TALLER),
    API_VENTA_CONEXION_ANULAR_OPORTUNIDAD("MSVCO_010",
            ERROR_API_VENTA_CONEXION_ANULAR_OPORTUNIDAD),
    API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_CORE("MSVCO_011",
            ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_CORE),
    API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_MDM("MSVCO_012",
            ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_MDM),
    API_VENTA_CONEXION_ENROLAMIENTO_PORTAL("MSVCO_014",
            ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL),
    API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_CAMBIOCLAVE("MSVCO_015",
            ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_CAMBIOCLAVE),
    API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_PRIMERLOGIN("MSVCO_016",
            ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_PRIMERLOGIN),
    API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_DESBLOQUEO("MSVCO_017",
            ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PORTAL_FLAG_DESBLOQUEO),
    API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_RESETEOCLAVE("MSVCO_018",
            ERROR_API_VENTA_CONEXION_ENROLAMIENTO_PROSPECTO_RESETEOCLAVE),
    API_VENTA_CONEXION_ENVIO_MAIL("MSVCO_030", ERROR_API_VENTA_CONEXION_ENVIO_MAIL),
    API_VENTA_CONEXION_PLANTILLA_DOCUMENTO("MSVCO_031", ERROR_API_VENTA_CONEXION_PLANTILLA_DOCUMENTO),
    API_VENTA_CONEXION_ENCRIPTA_PDF("MSVCO_034", ERROR_API_VENTA_CONEXION_ENCRIPTA_PDF),
    API_VENTA_CONEXION_BIOMETRIA_IMAGENES("MSVCO_035", ERROR_API_VENTA_CONEXION_BIOMETRIA_IMAGENES),
    API_VENTA_CONEXION_ENROLAMIENTO_IDG("MSVCO_045", ERROR_API_VENTA_CONEXION_ENROLAMIENTO_IDG),
    API_VENTA_CONEXION_AGREGAR_DISPODSITIVO("MSVCO_038", ERROR_API_VENTA_CONEXION_AGREGAR_DISPOSITIVO),
    API_VENTA_CONEXION_ACTUALIZAR_DISPOSITIVO("MSVCO_037", ERROR_API_VENTA_CONEXION_ACTUALIZAR_DISPOSITIVO),

    API_VENTA_SERVIDOR_CONFIG_FIRMA_ESIGN("MSVSE_001", ERROR_API_VENTA_SERVIDOR_CONFIG_FIRMA_ESIGN),
    API_VENTA_SERVIDOR_SOLICITUD_FIRMA_ESIGN("MSVSE_002", ERROR_API_VENTA_SERVIDOR_SOLICITUD_FIRMA_ESIGN),
    API_VENTA_SERVIDOR_FIRMA_ESIGN("MSVSE_003", ERROR_API_VENTA_SERVIDOR_FIRMA_ESIGN),
    API_VENTA_SERVIDOR_DETALLE_OPORTUNIDADES("MSVSE_004", ERROR_API_VENTA_SERVIDOR_DETALLE_OPORTUNIDADES),
    API_VENTA_SERVIDOR_SUBIR_DOCUMENTO_OPORTUNIDADES("MSVSE_005",
            ERROR_API_VENTA_SERVIDOR_SUBIR_DOCUMENTO_OPORTUNIDADES),
    API_VENTA_SERVIDOR_CREA_OPORTUNIDADES("MSVSE_006", ERROR_API_VENTA_SERVIDOR_CREA_OPORTUNIDADES),
    API_VENTA_SERVIDOR_ACTIVA_OPORTUNIDADES("MSVSE_007", ERROR_API_VENTA_SERVIDOR_ACTIVA_OPORTUNIDADES),
    API_VENTA_SERVIDOR_CATEGORIAS_TALLER("MSVSE_008", ERROR_API_VENTA_SERVIDOR_CATEGORIAS_TALLER),
    API_VENTA_SERVIDOR_DETALLE_TALLER("MSVSE_009", ERROR_API_VENTA_SERVIDOR_DETALLE_TALLER),
    API_VENTA_SERVIDOR_ANULAR_OPORTUNIDAD("MSVSE_010", ERROR_API_VENTA_SERVIDOR_ANULAR_OPORTUNIDAD),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO("MSVSE_011", ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_CORE("MSVSE_012",
            ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_CORE),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_MDM("MSVSE_013",
            ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_MDM),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL("MSVSE_015", ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_CAMBIOCLAVE("MSVSE_016",
            ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_CAMBIOCLAVE),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_PRIMERLOGIN("MSVSE_017",
            ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_PRIMERLOGIN),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_DESBLOQUEO("MSVSE_018",
            ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PORTAL_FLAG_DESBLOQUEO),
    API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_RESETEOCLAVE("MSVSE_019",
            ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_PROSPECTO_RESETEOCLAVE),
    API_VENTA_SERVIDOR_ENVIO_MAIL("MSVSE_031", ERROR_API_VENTA_SERVIDOR_ENVIO_MAIL),
    API_VENTA_SERVIDOR_PLANTILLA_DOCUMENTO("MSVSE_032", ERROR_API_VENTA_SERVIDOR_PLANTILLA_DOCUMENTO),
    API_VENTA_SERVIDOR_ENCRIPTA_PDF("MSVSE_035", ERROR_API_VENTA_SERVIDOR_ENCRIPTA_PDF),
    API_VENTA_SERVIDOR_BIOMETRIA_IMAGENES("MSVSE_036", ERROR_API_VENTA_SERVIDOR_BIOMETRIA_IMAGENES),
    API_VENTA_SERVIDOR_ENROLAMIENTO_IDG("MSVSE_046", ERROR_API_VENTA_SERVIDOR_ENROLAMIENTO_IDG),
    API_VENTA_SERVIDOR_AGREGAR_DISPODSITIVO("MSVSE_039", ERROR_API_VENTA_SERVIDOR_AGREGAR_DISPOSITIVO),
    API_VENTA_SERVIDOR_ACTUALIZAR_DISPOSITIVO("MSVSE_038", ERROR_API_VENTA_SERVIDOR_ACTUALIZAR_DISPOSITIVO),


    /* biometria */
    API_BIOMETRIA_SERVIDOR_SESION_PROGRESO("BMSES-006", ECatalogo.ERROR_API_BIOMETRIA_SESION_PROGRESO),
    REINTENTOS_API_BIOMETRIA("MSBIO_001", ECatalogo.ERROR_API_BIOMETRIA_REINTENTOS_SUPERADOS),

    /* anexa */
    API_ANEXA_SERVIDOR_LISTA_VALOR("MANSER_001", ECatalogo.ERROR_API_ANEXA_LISTA_VALOR_SERVIDOR),
    API_ANEXA_CONEXION_LISTA_VALOR("MANCON_001", ECatalogo.ERROR_API_ANEXA_LISTA_VALOR_CONEXION);

    /* Metodos para obtener Enum dado el codigo */
    private static final Map<String, ESubcatalogo> map = new HashMap<>();

    static {
        for (ESubcatalogo codigosECatalogo : ESubcatalogo.values()) {
            map.put(codigosECatalogo.codigo, codigosECatalogo);
        }
    }

    private final String codigo;
    private final IError catalogo;

    public static ESubcatalogo obtieneCatalogoPorCodigo(String codigo) {
        return map.getOrDefault(codigo, null);
    }
}
